live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#3b8eea"
cyan = "#29b8db"
green = "#23d18b"
magenta = "#d670d6"
red = "#f14c4c"
white = "#e5e5e5"
yellow = "#f5f543"

[colors.normal]
black = "#000000"
blue = "#2472c8"
cyan = "#11a8cd"
green = "#0dbc79"
magenta = "#bc3fbc"
red = "#cd3131"
white = "#e5e5e5"
yellow = "#e5e510"

[colors.primary]
background = "#1e1e1e"
foreground = "#cccccc"

[colors.selection]
background = "#565656"
text = "CellForeground"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.6666667"

[font]
size = 14

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Retina Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "command"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window.padding]
x = 2
y = 2

[window]
opacity=0.6

